---
ad_domain_admin_user: "{{ lookup('env', 'AD_DOMAIN_ADMIN_USER') }}"
ad_domain_admin_password: "{{ lookup('env', 'AD_DOMAIN_ADMIN_PASSWORD') }}"
ad_safe_mode_password: "{{ lookup('env', 'AD_SAFE_MODE_PASSWORD') }}"
