---
controller_credentials:
- name: HGS Certificate - host_guardian_service
  description: Credential for host_guardian_service
  organization: Default
  credential_type: HGS Certificate
  update_secrets: true
  inputs:
    certificate_path: '{{ certificate_path }}'
    certificate_password: '{{ vault_certificate_password }}'
- name: Root Certificate - host_guardian_service
  description: Credential for host_guardian_service
  organization: Default
  credential_type: Root Certificate
  update_secrets: true
  inputs:
    root_certificate_path: '{{ root_certificate_path }}'
- name: Directory Services Restore Mode - host_guardian_service
  description: Credential for host_guardian_service
  organization: Default
  credential_type: Directory Services Restore Mode
  update_secrets: true
  inputs:
    dsrm_password: '{{ vault_dsrm_password }}'
- name: Domain Controller Admin - host_guardian_service
  description: Credential for host_guardian_service
  organization: Default
  credential_type: Domain Controller Admin
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
- name: Domain Controller Join - host_guardian_service
  description: Credential for host_guardian_service
  organization: Default
  credential_type: Domain Controller Join
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
- name: Domain Join - host_guardian_service
  description: Credential for host_guardian_service
  organization: Default
  credential_type: Domain Join
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
- name: Temporary User Password - host_guardian_service
  description: Credential for host_guardian_service
  organization: Default
  credential_type: Temporary User Password
  update_secrets: true
  inputs:
    temp_password: '{{ vault_temp_password }}'
