---
controller_credentials:
- name: Domain Controller Admin Credential - activedirectoryhub
  description: Credential for activedirectoryhub
  organization: Default
  credential_type: Domain Controller Admin Credential
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
- name: Domain Controller Join Credential - activedirectoryhub
  description: Credential for activedirectoryhub
  organization: Default
  credential_type: Domain Controller Join Credential
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
- name: Domain Join Credential - activedirectoryhub
  description: Credential for activedirectoryhub
  organization: Default
  credential_type: Domain Join Credential
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
- name: Temporary User Password - activedirectoryhub
  description: Credential for activedirectoryhub
  organization: Default
  credential_type: Temporary User Password
  update_secrets: true
  inputs:
    password: '{{ vault_password }}'
