---
controller_credential_types:
- name: Domain Controller Admin Credential
  description: Credential type for Domain Controller Admin Credential
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Domain administrator username with permissions to promote domain
        controllers
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Domain administrator password
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
- name: Domain Controller Join Credential
  description: Credential type for Domain Controller Join Credential
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Username with permissions to join servers to the domain as domain
        controllers
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Password for domain controller join account
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
- name: Domain Join Credential
  description: Credential type for Domain Join Credential
  kind: cloud
  inputs:
    fields:
    - id: username
      type: string
      label: Username
      help_text: Username with permissions to join servers to the domain
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Password for domain join account
    required:
    - username
    - password
  injectors:
    extra_vars:
      username: !unsafe '{{ username }}'
      password: !unsafe '{{ password }}'
- name: Temporary User Password
  description: Credential type for Temporary User Password
  kind: cloud
  inputs:
    fields:
    - id: password
      type: string
      label: Password
      secret: true
      help_text: Temporary password used for initial user creation
    required:
    - password
  injectors:
    extra_vars:
      password: !unsafe '{{ password }}'
