---
- name: Restart Windows
  ansible.windows.win_reboot:
    msg: Restarting Windows server for Host Guardian Service configuration
    pre_reboot_delay: 5
    post_reboot_delay: 30
    reboot_timeout: 600
- name: Install root certificate for proxy access
  ansible.windows.win_shell: certutil -addstore -f -enterprise -user root "{{ root_certificate_dest_path }}"
